# To run execute: docker-compose -f this-file.name up
version: '3.3' # version of docker compose

services:
  wordpress:
    image: wordpress:latest #fetched latest image from docker hub if not available locally
    container_name: wordpress-container
    restart: always
    ports:
      - 8080:80 #map wp container port (80) to localhost at (8080)
      - 22:22
    volumes:                                                            
        - "./data/wp-plugins:/var/www/html/wp-content/plugins"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
       - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  adminer: #a little better phpAdminPanel                               
    image: adminer                                                      
    ports:                                                              
      - 8001:8080         
